[versions]
kgp = "2.3.0"
ksp = "2.3.4"
gratatouille-runtime = "0.2.1"
gratatouille-plugin = "0.2.1"
gradle-api = "8.8"
nmcp = "1.4.3-SNAPSHOT-90daa7892c17ddc91e613423be6948a7b4b5be65"

[libraries]
json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0"
okio = "com.squareup.okio:okio:3.16.4"
okhttp = "com.squareup.okhttp3:okhttp:5.3.2"
mockwebserver = "com.squareup.okhttp3:mockwebserver:5.3.2"
#noinspection NewerVersionAvailable
gradle-min = { module = "dev.gradleplugins:gradle-api", version.ref = "gradle-api" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
xmlutil = "io.github.pdvrieze.xmlutil:serialization:1.0.0-rc1"
kgp = { module = "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kgp" }
coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
gratatouille-runtime = { module = "com.gradleup.gratatouille:gratatouille-runtime", version.ref = "gratatouille-runtime" }
gratatouille-tasks-runtime = { module = "com.gradleup.gratatouille:gratatouille-tasks-runtime", version.ref = "gratatouille-runtime" }
nmcp-tasks = {module = "com.gradleup.nmcp:nmcp-tasks", version.ref = "nmcp"}

[plugins]
kgp = { id = "org.jetbrains.kotlin.jvm", version.ref = "kgp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kgp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
gratatouille = { id = "com.gradleup.gratatouille", version.ref = "gratatouille-plugin" }
librarian = { id = "com.gradleup.librarian", version = "0.2.2-SNAPSHOT-e8574739fa730c6118181ba7b8cf7f559a568fd0" }
nmcp = { id = "com.gradleup.nmcp", version.ref = "nmcp" }
compat = { id = "com.gradleup.tapmoc", version = "0.4.1-SNAPSHOT-86d664ab69b813963b91060ecce036be943088ed" }
