[versions]
kgp = "2.2.20"
ksp = "2.3.2"
gratatouille-runtime = "0.1.3"
gratatouille-plugin = "0.1.3"

[libraries]
json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.1"
okio = "com.squareup.okio:okio:3.8.0"
okhttp = "com.squareup.okhttp3:okhttp:4.12.0"
mockwebserver = "com.squareup.okhttp3:mockwebserver:4.12.0"
gradle-min = "dev.gradleplugins:gradle-api:8.8"
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
xmlutil = "io.github.pdvrieze.xmlutil:serialization:0.91.1"
kgp = { module = "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kgp" }
coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
gratatouille-wiring-runtime = { module = "com.gradleup.gratatouille:gratatouille-wiring-runtime", version.ref = "gratatouille-runtime" }
gratatouille-tasks-runtime = { module = "com.gradleup.gratatouille:gratatouille-tasks-runtime", version.ref = "gratatouille-runtime" }

[plugins]
kgp = { id = "org.jetbrains.kotlin.jvm", version.ref = "kgp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kgp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
gratatouille-wiring = { id = "com.gradleup.gratatouille.wiring", version.ref = "gratatouille-plugin" }
gratatouille-tasks = { id = "com.gradleup.gratatouille.tasks", version.ref = "gratatouille-plugin" }
librarian = { id = "com.gradleup.librarian", version = "0.2.2-SNAPSHOT-44b68f3cb157b53cd19d63b93c6eeae967d1da4a" }
nmcp = { id = "com.gradleup.nmcp", version = "1.2.1-SNAPSHOT-e592afcb0bceeb0cfd7adec28f8f3580a01831ff" }
compat = { id = "com.gradleup.compat.patrouille", version = "0.0.1-SNAPSHOT-9da44b3b93e36a196ae5afc9f7a79a46a82763cd" }
